#!/usr/bin/with-contenv bash

### Set Defaults
ADMIN_PASS=${ADMIN_PASS:-"admin"}
PLUGIN_ASN=${PLUGIN_ASN:-"TRUE"}
PLUGIN_CLAMAV=${PLUGIN_CLAMAV:-"TRUE"}
PLUGIN_EMAILS=${PLUGIN_EMAILS:-"TRUE"}
PLUGIN_GREYLISTING=${PLUGIN_GREYLISTING:-"TRUE"}
PLUGIN_MILTER=${PLUGIN_MILTER:-"FALSE"}
REDIS_HOST=${REDIS_HOST:-"redis.int.nforcer.com"}
REDIS_PORT=${REDIS_PORT:-"6379"}
REDIS_TIMEOUT=${REDIS_TIMEOUT:-"15s"}
REDIS_DB=${REDIS_DB:-"7"}
LOG_LEVEL=${LOG_LEVEL:-"info"} # error,warning,info,debug

### Set Password
sed -i -e '/password = /c\password  = "'${ADMIN_PASS}'";' /etc/rspamd/local.d/worker-controller.inc

### Set Log Level
sed -i -e '/level = /c\level = "'${LOG_LEVEL}'";' /etc/rspamd/local.d/logging.inc


### Setup Redis
cat <<EOF > /etc/rspamd/local.d/redis.conf
servers = "$REDIS_HOST:$REDIS_PORT";
db = "$REDIS_DB";
EOF

#sed -i -e '/servers = /c\servers = "'${REDIS_HOST}':'${REDIS_PORT}'";' /etc/rspamd/local.d/classifier-bayes.conf
sed -i -e '/servers = /c\servers = "'${REDIS_HOST}':'${REDIS_PORT}'";' /etc/rspamd/local.d/greylist.conf

### Setup Redis History
cat <<EOF > /etc/rspamd/local.d/history_redis.conf
servers = "$REDIS_HOST:$REDIS_PORT"; # Redis server to store history
key_prefix = "rs_history"; # Default key name
nrows = 2000; # Default rows limit
compress = true; # Use zstd compression when storing data in redis
EOF

if [ "$PLUGIN_DKIM" = "TRUE" ] || [ "$PLUGIN_DKIM" = "true" ];  then
	rspamadm dkim_keygen -b 2048 -s dkim -k /var/lib/rspamd/dkim/dkim.key > /var/lib/rspamd/dkim/dkim.txt
	chmod 440 /var/lib/rspamd/dkim/*
	cp -R /etc/rspamd/local.d/dkim_signing.conf /etc/rspamd/local.d/arc.conf	  
fi 

FEATURES_ENABLED=`set -o posix; set | sort | grep PLUGIN | grep TRUE |sed -e 's/PLUGIN_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
echo '** [rspamd] Enabling the following features: '$FEATURES_ENABLED

### Setup Persistent Storage
if [ ! -d /run/rspamd ]; then
	mkdir -p /run/rspamd
fi
mkdir -p /var/lib/rspamd/dkim
chown -R rspamd:rspamd /var/lib/rspamd /etc/rspamd /run/rspamd

mkdir -p /tmp/state
touch /tmp/state/rspamd-init
