#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/clamav-init ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
	set -x
	DEBUG_ARG="--debug" 
fi

echo ''
echo '** Starting clamav'
exec s6-setuidgid clamav clamd --foreground $DEBUG_ARG